 /******************************************************************************
 * File Name: ultrasonic.h
 * Author: Nardeen
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"

/* Initialize the ICU driver
Setup the ICU call back function.
Setup the direction for the trigger pin as output pin through the
GPIO driver */

void Ultrasonic_init(void);

/* Send the Trigger pulse to the ultrasonic. */
void Ultrasonic_Trigger(void);
 /*
  Send the trigger pulse by using Ultrasonic_Trigger function.
  Start the measurements by the ICU
   */

uint16 Ultrasonic_readDistance(void);


/*   This is the call back function called by the ICU driver.
    This is used to calculate the high time (pulse time) generated by
    the ultrasonic sensor */
 void Ultrasonic_edgeProcessing(void);



#endif /* ULTRASONIC_H_ */
