 /******************************************************************************
 * File Name: ultrasonic.c
 * Author: Nardeen
 *******************************************************************************/

#include "icu.h"
#include "gpio.h"
#include "avr/io.h"
#include <util/delay.h>

uint8 g_Count=0;
uint16 g_Time_High=0;

/* Initialize the ICU driver
Setup the ICU call back function.
Setup the direction for the trigger pin as output pin through the
GPIO driver */
void  Ultrasonic_edgeProcessing(void);

void Ultrasonic_init(void){
	Icu_ConfigType *config_type ={F_CPU_8 ,RISING };
	Icu_init(&config_type);
	Icu_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
}

/* Send the Trigger pulse to the ultrasonic. */

void Ultrasonic_Trigger(void){
	GPIO_writePin(PORTB_ID, PIN5_ID , LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID, PIN5_ID , LOGIC_LOW);

}

 /*
  Send the trigger pulse by using Ultrasonic_Trigger function.
  Start the measurements by the ICU
   */
uint16 Ultrasonic_readDistance(void){
	uint16 distance=0;
	Ultrasonic_Trigger();
	distance=(float)(g_Time_High)/ (57.7) ;
	return distance;
}


/*   This is the call back function called by the ICU driver.
    This is used to calculate the high time (pulse time) generated by
    the ultrasonic sensor */
 void Ultrasonic_edgeProcessing(void){
	 g_Count++;
	 if(g_Count==1) {
		 Icu_clearTimerValue();
		 Icu_setEdgeDetectionType(FALLING);
	 }

	 if(g_Count==2){
		 Icu_clearTimerValue();
		 Icu_setEdgeDetectionType(RISING);
		g_Count=0;
		g_Time_High = Icu_getInputCaptureValue();
	 }
 }
